language: ruby

rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - "jruby-9.1.5.0"
  - "ruby-head"

env:
  - COVERALL=1

cache:
  - bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.1.5.0

before_install:
  - gem install bundler
